apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: details
  labels:
    name: details
    hcmapp: mcmappdemo
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://raw.githubusercontent.com/ycao56/bookinfo/master/charts/details-mcm-0.1.5.tgz
      namespace: default

---

apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: ratings
  labels:
    name: ratings
    hcmapp: mcmappdemo
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://raw.githubusercontent.com/ycao56/bookinfo/master/charts/ratings-mcm-0.1.5.tgz
      namespace: default

---

apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: reviews
  labels:
    name: reviews
    hcmapp: mcmappdemo
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://raw.githubusercontent.com/ycao56/bookinfo/master/charts/reviews-mcm-0.1.5.tgz
      namespace: default
  dependencies:
  - destination:
      name: ratings
      kind: Deployable
    type: usesCreated

---

apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: bookinfo
  labels:
    name: bookinfo
    hcmapp: mcmappdemo
    servicekind: ApplicationService
    placementpolicy: bookinfo
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://raw.githubusercontent.com/ycao56/bookinfo/master/charts/productpage-mcm-0.1.5.tgz
      namespace: default
  dependencies:
  - destination:
      name: details
      kind: Deployable
    type: usesCreated
  - destination:
      name: reviews
      kind: Deployable
    type: usesCreated
    
---

apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: bookinfo
  labels:
    name: bookinfo
    hcmapp: mcmappdemo
placementRef:
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
  name: bookinfo
subjects:
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: bookinfo
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: ratings
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: reviews
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: details


---

apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: bookinfo
  labels:
    name: bookinfo
    hcmapp: mcmappdemo
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
      vendor: ICP
  clusterReplicas: 1
      
---

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo
  labels:
    app: bookinfo
    hcmapp: mcmappdemo
spec:
  selector:
    matchLabels:
      hcmapp: mcmappdemo
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment

---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: bookinfo
  labels:
    app: bookinfo
    hcmapp: mcmappdemo
spec:
  destination:
    kind: Deployable
    name: bookinfo
  source:
    kind: Application
    name: bookinfo
  type: contains
---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: details
  labels:
    app: bookinfo
    hcmapp: mcmappdemo
spec:
  destination:
    kind: Deployable
    name: details
  source:
    kind: Application
    name: bookinfo
  type: contains

---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: ratings
  labels:
    app: bookinfo
    hcmapp: mcmappdemo
spec:
  destination:
    kind: Deployable
    name: ratings
  source:
    kind: Application
    name: bookinfo
  type: contains

---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: reviews
  labels:
    app: bookinfo
    hcmapp: mcmappdemo
spec:
  destination:
    kind: Deployable
    name: reviews
  source:
    kind: Application
    name: bookinfo
  type: usesCreated
